/**
 * Writes app/favicon.ico from lib/brand.ts: the 16 px optical variant, then
 * the full mark at 32 and 48. Every other icon is generated by Next at build
 * time; favicon.ico must be a static file, so it is generated here and
 * committed. Rerun after changing the mark:
 *
 *   bun scripts/favicon.ts        (needs rsvg-convert, from librsvg)
 */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { FAVICON_SVG, MARK_SVG } from "../lib/brand";

const png = (svg: string, size: number) =>
  execFileSync("rsvg-convert", ["-w", `${size}`, "-h", `${size}`], {
    input: svg,
  });

const images = [
  { size: 16, data: png(FAVICON_SVG, 16) },
  { size: 32, data: png(MARK_SVG, 32) },
  { size: 48, data: png(MARK_SVG, 48) },
];

// ICO container with PNG payloads: 6 byte header, 16 bytes per entry, then the images.
const header = Buffer.alloc(6);
header.writeUInt16LE(0, 0);
header.writeUInt16LE(1, 2);
header.writeUInt16LE(images.length, 4);
let offset = 6 + 16 * images.length;
const entries = images.map(({ size, data }) => {
  const entry = Buffer.alloc(16);
  entry.writeUInt8(size, 0);
  entry.writeUInt8(size, 1);
  entry.writeUInt16LE(1, 4);
  entry.writeUInt16LE(32, 6);
  entry.writeUInt32LE(data.length, 8);
  entry.writeUInt32LE(offset, 12);
  offset += data.length;
  return entry;
});

const out = new URL("../app/favicon.ico", import.meta.url).pathname;
writeFileSync(
  out,
  Buffer.concat([header, ...entries, ...images.map((i) => i.data)]),
);
console.log(`Wrote ${out}`);
